### ISSUE TITLE
Support `args_len` non-qualification cells search

### ISSUE THREAD

**Issue by cosinlink** [nervosnetwork/ckb-indexer#14]
## Abstract
axon new project needs supports for more flexible cells search. 

### args_len non-qualification
```
pub struct SearchKey {
    script: Script,
    script_type: ScriptType,
    args_len: Option<Uint32>,
}
```

while `parameters`
- `args_len` == None
- `script.args` is empty

expect `return`
- all live cells that match `script_type`, `script.code_hash` and `script.hash_type`

**Comment by quake** [comment]
resolved by https://github.com/nervosnetwork/ckb-indexer/commit/7b9a2d79e2f8a4f2325951f4dedecc56e6ce04a7

indexer will return all cells/txs which match the `code_hash` and `hash_type` when query parameter of `script.args` is empty and `args_len` is none, example:
```
echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "get_cells",
    "params": [
        {
            "script": {
                "code_hash": "0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212",
                "hash_type": "data",
                "args": "0x"
            },
            "script_type": "type"
        },
        "asc",
        "0x64"
    ]
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
http://localhost:8116
```

**Comment by cosinlink** [comment]
It works for me.
Thank you @quake  ^_^
