### ISSUE TITLE
Support search cells by Script.args prefix

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/ckb-indexer#18]
Currently, ckb-indexer serialize Script key like this:
https://github.com/nervosnetwork/ckb-indexer/blob/60d397cf0d3e79f8d82f1e996644d870b1493401/src/indexer.rs#L85

Above code is equals to follow pseudo code:
```
key_script_part = code_hash([u8; 32]) ++ hash_type(u8) ++ args.length(u32) ++ args(Vec<u8>)
```

This design will stop us from prefix search `Script.args`, since the `args.length` is a variable. And `args.length = Script.length - 33`, means that it is a redundancy information.

If we design the Script key like this (just remove the `args.length` part):
```
key_script_part = code_hash([u8; 32]) ++ hash_type(u8) ++ args(Vec<u8>)
```

We would be able to search cells by Script.args prefix.

**NOTE: This design will change the data schema, which is a BREAKING CHANGE.**

**Comment by quake** [comment]
Currently ckb-indexer only supports fixed-length args prefix searches, for example, 2 blake160 hash of pubkey are composited into a script args, the total len of args should be fixed 40, you can prefix search scripts with first blake160 hash:  
```
script.args: first blake160 hash of pubkey (length 20)
args_len: 40
```

we can't support `order` and `filter.block_range` search options if we go with your design.
