### ISSUE TITLE
GLIBC_2.29' not found

### ISSUE THREAD

**Issue by jiangxianliang007** [nervosnetwork/ckb-indexer#24]
准备试用 ckb-indexer v0.2.0 版本，报了个glibc 错误，
ckb-indexer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ckb-indexer)

发现 ubuntu 18.04 最高的glibc 版本是GLIBC_2.27，是否需要在ubuntu 20 系统上 才能使用 最新的ckb-indexer 版本？

如果ubuntu 18.04 可以使用，是否可以说明下怎么 安装 GLIBC_2.29 ？

**Comment by driftluo** [comment]
在 ubuntu 18.04 上源码编译就可以了 @jiangxianliang007

**Comment by quake** [comment]
请问前一个版本 0.1.10 release binary 可以直接在你的 ubuntu 18.04 上运行吗?

**Comment by quake** [comment]
release binary 是通过 github action 创建的, 应该是他们最近的 build os 从 18.04 升级到了 20.04, 等我改一下 action build os 重新发个包. 在重新发布前, 只能通过自己编译来解决.

https://github.com/nervosnetwork/ckb-indexer/runs/2083320502?check_suite_focus=true#step:1:4
```
Operating System
  Ubuntu
  20.04.2
```

https://github.com/nervosnetwork/ckb-indexer/runs/1782005368?check_suite_focus=true#step:1:4
```
Operating System
  Ubuntu
  18.04.5
  LTS
```

**Comment by jiangxianliang007** [comment]
> 请问前一个版本 0.1.10 release binary 可以直接在你的 ubuntu 18.04 上运行吗?
0.1.10 可以的。
![image](https://user-images.githubusercontent.com/24754263/111111914-28bf1000-859a-11eb-81e1-bc79004aae58.png)

**Comment by jiangxianliang007** [comment]
> release binary 是通过 github action 创建的, 应该是他们最近的 build os 从 18.04 升级到了 20.04, 等我改一下 action build os 重新发个包. 在重新发布前, 只能通过自己编译来解决.
> 
> https://github.com/nervosnetwork/ckb-indexer/runs/2083320502?check_suite_focus=true#step:1:4
> 
> ```
> Operating System
>   Ubuntu
>   20.04.2
> ```
> 
> https://github.com/nervosnetwork/ckb-indexer/runs/1782005368?check_suite_focus=true#step:1:4
> 
> ```
> Operating System
>   Ubuntu
>   18.04.5
>   LTS
> ```

好的。

**Comment by quake** [comment]
已经重新发布

**Comment by jiangxianliang007** [comment]
ubuntu 18.04 可以使用了。
