### ISSUE TITLE
Support new rpc for indexer version info

### ISSUE THREAD

**Issue by EthanYuan** [nervosnetwork/ckb-indexer#32]
The startup of Godwoken node relies on the appropriate version of the indexer.

If there is a way to query the indexer version through rpc, it can avoid problems caused by the version being lower than the requirement.

So I think a new rpc method to get the indexer version is very useful.

**Comment by quake** [comment]
I created a PR https://github.com/nervosnetwork/ckb-indexer/pull/33, please help to review.

```
echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "get_indexer_info",
    "params": []
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
http://localhost:8116

{"jsonrpc":"2.0","result":{"version":"0.2.0"},"id":2}
```

**Comment by EthanYuan** [comment]
I compiled  and tested it, and it works fine. Thank you.
