### ISSUE TITLE
Cannot get genesis block from ckb node

### ISSUE THREAD

**Issue by oritwoen** [nervosnetwork/ckb-indexer#38]
By completing the issue: https://github.com/nervosnetwork/grants/issues/1 I encountered a certain obstacle, when starting the indexer with a synchronized node node receives such an error.

Node: `ckb 0.100.0-rc2 (35b2111 2021-07-16)`
Indexer: `ckb-indexer 0.2.1`

```sh
[2021-07-28T08:50:04.107Z ERROR ckb_indexer::service] cannot get genesis block from ckb node, error: Failed to parse server response as Option < BlockView >: missing field `uncles_hash`
```

**Comment by quake** [comment]
ckb-indexer 0.2.1 is not compatible with ckb pre-release version, please use [ckb 0.43.1 (15427e0 2021-07-16)](https://github.com/nervosnetwork/ckb/releases/tag/v0.43.1)
