### ISSUE TITLE
The balance query seems to be inaccurate

### ISSUE THREAD

**Issue by GXKe** [nervosnetwork/ckb-indexer#40]
address ckt1qyqfql5wuaxuwmudtv6n7sdwjmr4lnlf08jsgde3c5

capacity":12200852944,"block_hash":"0x69ad812567190c52353d690b5c33588904e2841177e8f4fbc83944144c0bfe02","block_number":2341191

The result of indexer query is 122.00852944
However, the browser shows a balance of 28462095

https://explorer.nervos.org/aggron/address/ckt1qyqfql5wuaxuwmudtv6n7sdwjmr4lnlf08jsgde3c5

**Comment by GXKe** [comment]
![Uploading image.png…]()
Incomplete browser data synchronization?

**Comment by quake** [comment]
what's your ckb-indexer version? and please provide the detail curl command you used to call the rpc.

**Comment by GXKe** [comment]
indexer 0.2.2

**Comment by GXKe** [comment]
![image](https://user-images.githubusercontent.com/4132888/128306426-b339b7dc-2254-4554-860c-ef40efd8e1bf.png)

**Comment by GXKe** [comment]
I use CKB SDK go

**Comment by GXKe** [comment]
![image](https://user-images.githubusercontent.com/4132888/128306798-6117c565-9a99-46da-af4a-61aa898001c7.png)

**Comment by quake** [comment]
it's ckb-explorer issue, the balance of miner is incorrect, I have report this issue to ckb-explorer.
