### ISSUE TITLE
Archive structure is non-standard.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb-indexer#43]
The structure of the compressed archive is not as expected:

- There is a second archive within the first archive. In the Linux build a tar.gz is within a zip.
- The files are not contained within a directory once expanded. They dump to the current directory.

For reference, please compare the results of the CKB node to the CKB Indexer after expansion in the screenshot below.

![20210824000026](https://user-images.githubusercontent.com/37931/130571830-75da188a-0e2a-417e-96d1-070a9a8c39c6.png)

**Comment by quake** [comment]
waiting for https://github.com/actions/upload-artifact/issues/39

**Comment by quake** [comment]
resolved in https://github.com/nervosnetwork/ckb-indexer/releases/tag/v0.4.0
