### ISSUE TITLE
Logging verbosity cannot be changed using the common `-v` switch

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb-indexer#44]
The verbosity of the logging seems to only be changeable using the `RUST_LOG` environmental variable. It would be much more user-friendly to use the more common `-v` switch to increase the verbosity of the logging being displayed on the screen.

Examples:

`RUST_LOG=info ./target/release/ckb-indexer -s /tmp/ckb-indexer-test`
changes to:
`./target/release/ckb-indexer -s /tmp/ckb-indexer-test -v`

`RUST_LOG=debug ./target/release/ckb-indexer -s /tmp/ckb-indexer-test`
changes to:
`./target/release/ckb-indexer -s /tmp/ckb-indexer-test -vv`

`RUST_LOG=trace ./target/release/ckb-indexer -s /tmp/ckb-indexer-test`
changes to:
`./target/release/ckb-indexer -s /tmp/ckb-indexer-test -vvv`

**Comment by x777** [comment]
How to enable logging on Windows?

**Comment by quake** [comment]
the log create is the de-facto logging API in Rust, convenient to use environment variables to control different crate log output level, for example, we can set the default level to `WARN` and `jsonrpc_client_transports` crate level to debgu:

```
RUST_LOG=warn,jsonrpc_client_transports=debug ./target/release/ckb-indexer -s /tmp/ckb-indexer-test
```

**Comment by jordanmack** [comment]
I disagree with the decision to close this. Using `RUST_LOG` is not intuitive or friendly to most users. Using `-v` is a far more common convention for most command-line applications regardless of the underlying language used.

I also use the log crate in several Rust applications. There is nothing preventing the support of both `RUST_LOG` and `-v` at the same time.
