### ISSUE TITLE
cannot get local_node_info from ckb node

### ISSUE THREAD

**Issue by tianlitao** [nervosnetwork/ckb-indexer#46]
我在本地跑indexer是正常的，但是在阿里云服务器上执行，提示如下报错
![image](https://user-images.githubusercontent.com/7892962/145835577-16a5084f-5138-4a7d-9d2b-975e8f0f6e7f.png)

**Comment by quake** [comment]
ckb-indexer 需要连接一个 ckb 节点的 rpc, 默认不给参数的话, 会去连接 127.0.0.1:8114, 你可以通过 -c 参数去连接不同的地址:
```
-c tcp://192.168.x.x:8114
```
