### ISSUE TITLE
Add custom rule in ckb-indexer 

### ISSUE THREAD

**Issue by xcshuan** [nervosnetwork/ckb-indexer#51]
At present, ckb-indexer runs get_cells, get_transactions through scan matching, which will gradually increase the cost of this operation, which will lead to a problem similar to ETH, where the cost of state reading increases with the size of the state.

For specific applications, scan matching will affect the access speed and may affect the response speed of the application.

Can ckb-indexer add custom rules, such as specifying lock_script, type_script, lock_code_hash, type_code_hash or other rules, and then pre-store the involved cells and transactions, put them in the cache to speed up access. When the request hits the cache, it can return quickly.

Because different projects only pay attention to their own cells, they definitely hope that the access speed of related cells will not be affected by other cells, such as certain types of sUDT cells, or cells of a certain Layer2 protocol.

**Comment by quake** [comment]
This is a great idea, and we will look into how to implement this.

**Comment by quake** [comment]
@xcshuan Can you review if this PR #57 meets your needs?

**Comment by xcshuan** [comment]
> @xcshuan Can you review if this PR #57 meets your needs?

Hello, I haven't read this pr in depth, its function is to set some rules for partial-indexing, and the data that does not meet the custom rules will no longer be stored, which is a very useful function.

But what I'm talking about is not the problem of storage space occupancy, but the problem of state explosion which leads to increased access time, similar to the difference between Ethereum's historical transactions and the current state.

Partial-indexing can certainly speed up cell access, but it also makes it difficult to provide a full indexer service.

I think in addition to partial-indexing, indexer can also add an option to cache-indexing. The data that meets the custom rules is stored in a `special db`, and other data is stored in another db. When processing a request, if its SearchKey meet the custom rules, the indexer can quickly scan in the `special db`, otherwise the indexer can only scan in the db where all the data is stored.

**Comment by quake** [comment]
ckb-indexer uses rocksdb as storage, which is a LSM tree. When designing the data structure of the ckb-indexer storage and the rpc methods, we use prefix search, this range scan does not bring significant read performance degradation due to the growth of data volume, especially after LSM tree leveled compaction.

We will not consider adding this optimization for now until there is a performance bottleneck.

**Comment by xcshuan** [comment]
Ok, since the parsing and filtering of the rules is implemented, I think it is enough.
