### ISSUE TITLE
Add a `with_data` param to `get_cells` 

### ISSUE THREAD

**Issue by homura** [nervosnetwork/ckb-indexer#52]
## Motivation

As a dApp developer, we may need to upgrade the script, and when the script is upgraded, the `OutPoint` in `CellDeps` will be updated, and the dApp developer can use `get_cells` to get the `OutPoint` of the latest `CellDep`, but this `Cell` often has a large size and is not dApps need data

It is useful to add a parameter `with_data` to `get_cells`, which can be set to false by default to keep compatibility.

```ts
let dep_cell = await ckb_rpc.get_live_cell(before_out_point, false /* with_data */)

if (dep_cell.status == "live") {
  return before_out_point
}

let upgraded_cell = await indexer_rpc.get_cells(..., false /* with_data */)
return upgraded_cell.out_point
```

## References

- [get_live_cell](https://github.com/nervosnetwork/ckb/blob/develop/rpc/README.md#method-get_live_cell)

**Comment by quake** [comment]
I think the `with_data` param should be set to default `true` to keep compatibility
