### ISSUE TITLE
Support query script by lock script hash

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/ckb-indexer#58]
Sometime we want query the script by lock script hash. 

The typical example is query [sudt](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0025-simple-udt/0025-simple-udt.md#issuemint-sudt) owner's script. Now we can query the script in ckb-cli and explorer:
*  `ckb-cli wallet get-live-cells --lock-hash <lock-hash>`
*  explorer https://pudge.explorer.nervos.org/address/0x787e97af6860c58fcecd12653714330c003f5b960e09f027295a49e3c41d609f 

But if user want query the script in sdk code,  it's not easy to do it.

So, can `ckb-indexer` provider a way to query the script by lock script hash?

**Comment by quake** [comment]
I think you can use this sudt type script to query the first transaction to find the issuer's lock script, and then use the issuer's lock script to get the live cell:

```bash
echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "get_transactions",
    "params": [
        {
            "script": {
                "code_hash": "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4",
                "hash_type": "type",
                "args": "0x6fe3733cd9df22d05b8a70f7b505d0fb67fb58fb88693217135ff5079713e902"
            },
            "script_type": "type"
        },
        "asc",
        "0x1"
    ]
}' \
| curl -H 'content-type: application/json' -d @- \
https://testnet.ckb.dev/indexer
```

```json
{
  "jsonrpc": "2.0",
  "result": {
    "last_cursor": "0xa0c5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4016fe3733cd9df22d05b8a70f7b505d0fb67fb58fb88693217135ff5079713e902000000000009069c000000010000000001",
    "objects": [
      {
        "block_number": "0x9069c",
        "io_index": "0x0",
        "io_type": "output",
        "tx_hash": "0xef0cd57d61d86dfe0147f7dc786710bb797ba23769318a2884a2cffa5346d992",
        "tx_index": "0x1"
      }
    ]
  },
  "id": 2
}
```
