### ISSUE TITLE
ckb-indexer failed to start

### ISSUE THREAD

**Issue by guomaoqiu** [nervosnetwork/ckb-indexer#66]
When the ckb-indexer is started, the following problems occur. Can you help to troubleshoot the cause? The storage uses remote NFS, and the NFS service is currently normal.
![image](https://github.com/nervosnetwork/ckb-indexer/assets/9714859/a54a6e83-dd3e-4624-8294-a3bbc6b452fa)

**Comment by quake** [comment]
are you using multiple ckb-indexer instances to access the same NFS storage folder? which is not supported,  you may try to delete the `LOCK` file and restart if you are not using multiple instances.

**Comment by guomaoqiu** [comment]
Hello, no, our individual services are all NFS storage volumes that are used alone.

I can see this LOCK file, are you sure you can delete this file? Will there be any impact?

**Comment by guomaoqiu** [comment]
> are you using multiple ckb-indexer instances to access the same NFS storage folder? which is not supported, you may try to delete the `LOCK` file and restart if you are not using multiple instances.

Hello, no, our individual services are all NFS storage volumes that are used alone.

I can see this LOCK file, are you sure you can delete this file? Will there be any impact?

**Comment by doitian** [comment]
> > are you using multiple ckb-indexer instances to access the same NFS storage folder? which is not supported, you may try to delete the `LOCK` file and restart if you are not using multiple instances.
> 
> Hello, no, our individual services are all NFS storage volumes that are used alone.
> 
> I can see this LOCK file, are you sure you can delete this file? Will there be any impact?

Double check there is no running ckb-indexer processes, then It's OK to delete the LOCK file. If ckb-indexer complains that the db file is corrupted, you have to delete the data directory to let ckb-indexer recreates the index, or copy an existing data directory from another instance.

If you are not running multiple instances, it's likely the indexer process has exited abnormally, which has a change to leave a corrupted database.

**Comment by guomaoqiu** [comment]
According to your method, the LOCK file has been deleted, and now the log after restarting is as follows, should this be normal?
![image](https://github.com/nervosnetwork/ckb-indexer/assets/9714859/7a3be459-c0f9-4ba6-a874-2c1e5c06e158)
@doitian

**Comment by quake** [comment]
it's normal

**Comment by guomaoqiu** [comment]
Thank you for your help with the investigation!

**Comment by quake** [comment]
btw, ckb-indexer has been merged into the ckb node since v0.106.0, we recommend you to use the ckb node instead of this standalone service if you are running ckb v0.106.0 or later, which is more efficient and easier to setup, it can be enabled by `--indexer` command line option when starting the ckb node or by setting `Indexer` module in the ckb.toml config file's rpc section.
