### ISSUE TITLE
Support connecting node via HTTPs

### ISSUE THREAD

**Issue by katat** [nervosnetwork/ckb-indexer#8]
Hi @quake 

We got an issue report when it is trying to connect with a node via HTTPs. Here is the error thrown from the lumos indexer, which might be originated from ckb-indexer? https://github.com/nervosnetwork/lumos/issues/77

**Comment by quake** [comment]
resolved by https://github.com/quake/ckb-indexer/commit/e4f055d618d9b1bc36a45548ae88d86bdf0c2c19

tested with `https://lina.ckb.dev`
```
RUST_LOG=info ./target/release/ckb-indexer -s /tmp/ckb-indexer-test -c https://lina.ckb.dev
```
